"""
Session token id.

Revision ID: 51534ea49307
Revises: 951db5b97121
Create Date: 2024-12-16 14:12:06.242403

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51534ea49307"
down_revision: str | None = "951db5b97121"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auth_session", sa.Column("id", sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auth_session", "id")
    # ### end Alembic commands ###
