"""
Work Profile.

Revision ID: 55fb25b0b257
Revises: b859c61603f1
Create Date: 2025-01-10 16:01:25.165262

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55fb25b0b257"
down_revision: str | None = "b859c61603f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user__work_profile",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "specialization",
            sa.Enum("BACKEND", "FRONTEND", "QA", "DESIGNER", name="specialization"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user__user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user__work_profile")
    sa.Enum("BACKEND", "FRONTEND", "QA", "DESIGNER", name="specialization").drop(op.get_bind())
    # ### end Alembic commands ###
